### PR TITLE
Function libraries and call semantics

### PR DESCRIPTION
**Pull request by nokome**
## Why

This PR is needed because of updates to the definition of function libraries in JS and other languages including:

- changes to how functions are called (allowing for variadic and extensible keyword arguments)

- allowing functions to be defined dynamically in external execution contexts (e.g. Node.js Python, R) e.g. in `libdh`

- changes in function definitions away from XML towards native syntax for each language (e.g. JSDoc)

For more details see  https://github.com/stencila/libcore/pull/20 and https://github.com/stencila/node/pull/30

https://github.com/stencila/libcore/pull/20 needs to be completed, merged and published before merging this.

## What

- mostly refactoring/renaming

- does add an undocumented 'hack' to allow functions to be defined within a cell - this is really useful for less experienced developers to test that a function and its documentation works. To be decided if this remains undocumented, is documented, or removed (and a perhaps function definition UI added instead). An example or defining a function definition in Javascript using the Node.js context:

image

### CODE REVIEW

**Comment by oliver----** [comment]
Nice!

**Comment by oliver----** [comment]
@nokome better to rebase onto latest develop.
Your changes are orthogonal though, just better to have it moved to the latest state.

**Comment by nokome** [comment]
OK, I think this is finally ready to merge. More work needs to be done on several things including

- function usage tooltip and help panel (showing alternative parameter type signatures, better rendering of help)
- `JsContext` call semantics (matching named arguments to parameter names)
- removing code that is now unused (e.g `FunctionDocument`)

But this iteration is compatible with the latest version of libcore which has better documentation and things like a variadic sum function (finally :tada:) - so we should merge it in for the next release :)

image

**Comment by nokome** [comment]
Just been testing the integration with Stencila Desktop. Simulanteous, reactive calculation of a sum in different languages :roll_eyes: 

peek 2018-05-02 20-59

**Comment by oliver----** [comment]
On the long run I would like to see this also available for the `js` context. Maybe we can address this together with a webworker'isation of the JsContext.

**Comment by oliver----** [comment]
Couldn't get this running. Will let you finish the `stencila-desktop` integration first and then try again.

**Comment by nokome** [comment]
I've merged this.

The main change from the screenshots above has been to treat functions as first-class objects that can be returned from cells. When a function is an output from a cell it is registered in a `local` library.

>  I would like to see this also available for the js context (in browser). Maybe we can address this together with a webworker'isation of the JsContext.

Sounds good. I was hoping we could have just one implementation of a `JavascriptContext` https://github.com/stencila/node/blob/master/lib/contexts/JavascriptContext.js#L10 which would be used here and as a base class for `Node Context`

One aspect of this PR to note is that the `Engine` is now a property of the `host`. Prior to this PR we were actually instantiating two engines (but only running one). I have kept the one inside the host because the host needs to create execution contexts and have them register libraries (including `JsContext`) before it starts the engine. 

I found the whole app setup/initialisation pretty confusing with multiple nested functions e.g. `setupStencilaContext`, `_setupStencilaChildContext` and it seems that it would be good to refactor and simplify sometime (at which pint we can decide onthe best place for the engine to live).

**Comment by oliver----** [comment]
I agree, the setup is confusion at the moment. Let's improve this later on.

**Pull request merged**
