### PR TITLE
WIP: Functions

### PR DESCRIPTION
**Pull request by nokome**
Work in progress to add `Functions` as "first class citizens" just like `Documents` and `Sheets`. See #310 

This requires the `substance#improvements` branch.

Try `node make test:one -f "tests/function/functions.test.js"`

### CODE REVIEW

**Comment by michael** [comment]
Interesting to provide multiple implementations (different languages) for one function. I wonder how we choose one implementation on execution?

**Comment by nokome** [comment]
I envisage three criteria for choosing amongst implementations:

1. Availability: if you don't have an execution context capable of running an implementation (e.g. in R), then you'd have to use on of the other implementations (e.g. JS)

2. Proximity: where possible execution should be performed in the same context as the data, rather than transferring data between contexts e.g if you have a 1mil row data frame in an R context then it's better to execute `aggregate` there instead of transporting the data to the clients to run in JS

3. Efficiency: faster implementations should be preferred over slower ones. Although in most instances proximity is likely to outweigh computation speed, in some instance it may make sense to transfer whole parts of the execution graph to another, faster context.

**Comment by michael** [comment]
That sounds like a smart strategy! :) Let's just try not to optimize from the start. I agree the format should allow for multiple implementations. However we could start off with always selecting the first lang, so we can push implementing that selection logic to later (could be a source of errors too).

**Comment by nokome** [comment]
Yeah, totally. Just trying to get the schema to be flexible enough to allow for these types of things later, like you said "let’s try to start with something we can stick with for a while". Initially, I imagine we'll be focussing on just the one JS implementation.

**Comment by nokome** [comment]
Almost completed a first iteration of this. Still to do:

- XML-based (instead of JSON based) value specifications for default parameter values, and test argument and result values

- check that implementation types are consistent with parameter types when function is defined

- compile implementation code from external files e.g. `sum.fun.xml, sum.fun.js, sum.fun.r`

- quick documentation write up

**Comment by michael** [comment]
Looking good! Could you base this on the 'bloody-edge' branch? We created this one to be able to merge our experimental stuff more frequently.

**Comment by nokome** [comment]
This is now rebased to `bloody-edge` branch. Add `<code include="...">` to allow for source code in external files for each implementation. In the process of simplifying the schema to make definitions less verbose. Then should be close to finalising this first round!

**Comment by michael** [comment]
I'll close this PR and create a new one against bloody-edge, which you can merge once you are ready with the final iteration!

**Pull request closed without merging**
