### PR TITLE
Tests and Fixes

### PR DESCRIPTION
**Pull request by oliver----**
# Why?

At the moment, a lot of Stencila's functionality is not test covered.  This PR is about to change this.

# What?

- tests on model level (manipulations, commands etc.)
- some UI tests
- ...

> Note: this is just the first iteration. During this iteration I have don a bunch of refactors which I want to be merged ASAP. To be continued...

### CODE REVIEW

**Comment by oliver----** [comment]
@Integral don't be too sad. I will start over.

**Comment by Integral** [comment]
No worries, I'm ok with that ;)

**Comment by nokome** [comment]
@oliver----: thanks for picking this up, will be great to have more tests

**Comment by oliver----** [comment]
Calling this a first iteration.

**Pull request merged**
