### PR TITLE
Projects

### PR DESCRIPTION
**Pull request by nokome**
Adds initial support for projects in CLI and Node.js bindings.

### CODE REVIEW

**Comment by nokome** [comment]
@alex-ketch Could you have a look at this PR and see if it meets your needs for the desktop. I've added functions for getting a project from the filesystem including files . Files are keyed by canonical absolute path (for implementing updates via a file watcher) e.g.

```sh
> cargo run show test/fixtures/projects/mid -f json
Stencila CLI is in alpha testing.

{
  "name": "mid",
  "theme": "stencila",
  "files": {
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/a": {
      "path": "a",
      "isDir": true,
      "modified": 1620801984,
      "size": 4096
    },
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b": {
      "path": "b",
      "isDir": true,
      "modified": 1620808374,
      "size": 4096
    },
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b/1.txt": {
      "path": "b/1.txt",
      "isDir": false,
      "modified": 1620808374,
      "size": 0,
      "mediaType": "text/plain"
    },
```

I plan on implementing the file watching next with updates to the project JSON published on the "project:<canonical-of-project>" pubsub topic channel with subscriber function able to be passed to the `projects.open` function e.g.

```ts
projects.open("./some/relative/path", (topic: string, project: Project) => {
   /// Do something with the updated project object
})
```

**Comment by alex-ketch** [comment]
@nokome For the client UI needs it would be desirable to have a way of resolving the hierarchy of the structure.
Something along these lines would work:

```diff
{
  "name": "mid",
  "theme": "stencila",
  "files": {
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/a": {
      "path": "a",
      "isDir": true,
      "modified": 1620801984,
      "size": 4096,
+     "chidlren/files/?": []
    },
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b": {
      "path": "b",
      "isDir": true,
      "modified": 1620808374,
      "size": 4096,
+    "chidlren/files/?": [
+      "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b/1.txt"
+    ]
    },
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b/1.txt": {
      "path": "b/1.txt",
      "isDir": false,
      "modified": 1620808374,
      "size": 0,
      "mediaType": "text/plain"
    }
  }
}
```

**Comment by nokome** [comment]
Thanks @alex-ketch. I've made those changes. The differences from above:

- added `parent` and `children` properties
- removed `isDir` since it can be inferred from `children !== undefined`
- used `Project.path` rather than `root`

```json
{
  "name": "mid",
  "theme": "stencila",
  "path": "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid",
  "files": {
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid": {
      "path": "",
      "modified": 1620808374,
      "size": 4096,
      "parent": "/home/nokome/stencila/repos/stencila/test/fixtures/projects",
      "children": [
        "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/a",
        "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b",
        "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/c",
        "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/d",
        "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/e"
      ]
    },
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/a": {
      "path": "a",
      "modified": 1620801984,
      "size": 4096,
      "parent": "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid",
      "children": []
    },
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b": {
      "path": "b",
      "modified": 1620808374,
      "size": 4096,
      "parent": "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid",
      "children": [
        "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b/1.txt"
      ]
    },
    "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b/1.txt": {
      "path": "b/1.txt",
      "modified": 1620808374,
      "size": 0,
      "mediaType": "text/plain",
      "parent": "/home/nokome/stencila/repos/stencila/test/fixtures/projects/mid/b"
    },
```

**Comment by alex-ketch** [comment]
Thanks @nokome, the new bindings are working great 💖
Screenshot 2021-05-13 at 14 57 21@2x

If I could ask for one other field, having the `name` for all files/folders would be great and avoid having to do string replacements on the client (and this have to deal with OS specific path separators) 🙏

```diff
{
  "/Users/ketch/Work/Stencila/Demos/Pastoll et al/elife-52258.rmd.media/fig1-figsupp4.jpg": {
    "format": "jpg",
    "mediaType": "image/jpeg",
    "modified": 1611203792,
    "parent": "/Users/ketch/Work/Stencila/Demos/Pastoll et al/elife-52258.rmd.media",
    "path": "elife-52258.rmd.media/fig1-figsupp4.jpg",
+   "name": "fig1-figsupp4.jpg",
    "size": 99458
  }
}
```

**Comment by nokome** [comment]
Looks good @alex-ketch. What about dropping `path` and adding `name`? Path bothers me because it is sort of redundant / confusing given that the absolute path is used as the  key. Do you use `path`?

**Comment by nokome** [comment]
I'm going to merge this now, it seems to be in pretty good shape, although as always, improvements could be made (e.g. parrallel `FileRegistry` loading.

**Pull request merged**
