### PR TITLE
Add decoding and encoding of Jupyter Notebooks

### PR DESCRIPTION
**Pull request by nokome**
This PR ports the encoding and decoding of Jupyter Notebooks from Encoda to the `decode::ipynb` and `encode::ipynb` Rust modules. Advantages of having this functionality implemented in Rust include:

- no need to install a plugin to open and save as Jupyter Notebooks
- less brittle than using a plugin
- speed, including using delegating to conversion functions for `md` and `html` already implemented in Rust

### CODE REVIEW

**Comment by nokome** [comment]
@alex-ketch I've made some good progress decoding of `ipynb` notebooks including handling of Makrdown and code cells and most code cell outputs. Some thing I am aiming to do today:

- [ ] Decoding of `{{expr}}` in Markdown to `CodeExpression`s
- [ ] Convert `stderr` streams and `errors` into `CodeError`s
- [ ] Handle Plotly and Vega outputs
- [ ] Add `decode-txt` feature (to complement `encode-txt`) to convert plain text outputs to numbers etc
- [ ] Implement encoding and end-to-end encode-decode tests

I'll followup with progress and a screenshot 📷 at the end of the day.

**Comment by nokome** [comment]
Got most of the above done today, and as promised here's a screenshot :)

image

The HTML encoding of Plotly and Vega images is not done yet. Also, because the CSS in the preview pane is broken you make want to consider demoing using `cargo run -- open fixtures/articles/simple.ipynb` and then changing the theme e.g. http://127.0.0.1:9000/fixtures/articles/simple.ipynb?theme=elife

**Comment by alex-ketch** [comment]
Thanks for this @nokome 💖
I can confirm that I've been able to use this branch to preview `ipynb` files, and see the previews update when making changes in Jupyter.
Should be enough for me to create the necessary workflows I want to demo.

**Comment by nokome** [comment]
I've completed all of the check boxes above and things are fairly well tested so will merge now.

**Pull request merged**
