### PR TITLE
WIP: Plotly function

### PR DESCRIPTION
**Pull request by oliver----**
# Why?

At the moment, the `libcore` `plot()` function is not very useful.
Instead of inventing our own plotting API this PR introduces a `libcore `function for Plotly.
 
# What?

The introduced function does not do much more than just wrapping arguments into an `object` of type `plotly`, plus possibly some argument coercion for convenience.

> This PR requires https://github.com/stencila/libcore/pull/21 to be merged and published.

### CODE REVIEW

**Comment by oliver----** [comment]
stencila-plotly

**Comment by oliver----** [comment]
@michael what we said

**Comment by oliver----** [comment]
https://plot.ly/javascript/basic-charts/

**Comment by oliver----** [comment]
image

**Comment by nokome** [comment]
Thanks for doing this. I was going to do it this morning so it was a pleasant surprise to see I didn't need to! Shall we merge it?

**Comment by oliver----** [comment]
I think it is a pretty simple change.
We should first merge the PR on libcore, publish, update the package.json here, and then merge.

**Comment by nokome** [comment]
Yes, I'm doing the libcore publish now. Will update package.json and do the merge.

**Comment by oliver----** [comment]
Thanks!

**Comment by nokome** [comment]
Merging now. Made some quick tweaks to `plotly` function over in libcore to add layout defaults for axes.

**Comment by michael** [comment]
Very, just started playing around with it a bit. @nokome thanks for merging into develop. 

@oliver---- regarding the function help tooltip, I agree. Maybe what we could do is showing it only while the cursor is over the function name, and disable the display while over the signature?

**Pull request merged**
