### PR TITLE
Transclusion

### PR DESCRIPTION
**Pull request by oliver----**
Fixes implementation to consider cells from different resources.

### CODE REVIEW

**Comment by oliver----** [comment]
@michael I reverted to what I had yesterday and added some lines. sigh.

**Comment by oliver----** [comment]
@michael can u try a bit? and merge if you are happy.

**Comment by oliver----** [comment]
This also resolves a regression with colliding cell ids after we have introduced multiple docs.

**Comment by oliver----** [comment]
stencila-transclusions

**Comment by nokome** [comment]
@oliver---- nice! thank you!

BTW: improving that plot function is high on my to do list - I will get back to those related PRs over the next few days!

**Comment by oliver----** [comment]
Hehe... I thought you would spot that ;)

**Comment by michael** [comment]
This feels just awesome! :)

Some thoughts:

- would be nice to be able to follow such links, like command click takes you to the transcluded range in the sheet
- to transclude datasets it would be nice to somehow say, i want all rows for columns A:C, so when a new row gets entered in the sheet, this change is reflected in the document where the dataset is used
- as you already mentioned we need a smooth transition between the docs, and keeping the scroll position (will work on that)

**Comment by michael** [comment]
👍 for merging

**Comment by nokome** [comment]
In addition to @michael's suggestions, it would be great to be able to transclude the entire sheet ie dataset.

**Pull request merged**
