### PR TITLE
feat(web): web components for block node types

### LINKED ISSUE #1925: feat(paragraph node): Custom paragraph node
### Summary

Implement custom paragraph node web component

### Reference Issues

_No response_

### Implementation PR

_No response_

### PR DESCRIPTION
**Pull request by nokome**
Closes #1925 #1926 #1927 (maybe #1928 #1930).

### CODE REVIEW

**Comment by nokome** [comment]
I've fixed the `Entity.documentView()` method so that it walks up out of the shadow root to find the nearest view. This can be used to render nodes differently in different views (e.g. for a paragraph not showing the `content` property in `source` view):

image

image

**Comment by nokome** [comment]
I've added the "DOM HTML" as a format to the source view (during development only for now) so that it is easy for us to see which properties of a node are slots and which are attributes.

image

**Comment by nokome** [comment]
This is my suggestion for what we work on today for this PR:

#### @kusalekanayake

- create some designs for `BlockInfobox` (or whatever we call the popup card that shows the authors (and maybe other details later) of different types of block nodes). I have in mind an icon and title for the type of node, and a stacked list of authors with avatars/icons (e.g. person v org v ai) and names for each

- work with @simonwinter to implement these designs to get familiar with `TWLitElement` etc

#### @simonwinter

- add components for the node types that exist in `authors` properties:

  - [ ] `Person` (stubbed out already but to be based off `TWLitElement` and may need more properties)
  - [ ] `SoftwareApplication`
  - [ ] `Organization`

- work with @kusalekanayake on the design and implementation of authors list

#### @mike-parkin

- pair program with @nokome to factor out the `ObjectClient` from the `SourceView` without breaking the breadcrumbs in the bottom panel

- add a `DomClient` and invisible element to the `SourceView` and in `tooltipOnHover` use `element.getElementById` to get the web component for the node and show it as the tooltip

#### @nokome 

- work with @mike-parkin on the above

- progressively add components and ProseMiror `NodeSpec`s for other node types:

  - [x] Paragraph
  - [ ] Heading
  - [ ] List
  - [ ] Figure

**Comment by kusalekanayake** [comment]
SourceViewWithAttributions
Will finalise design soon but looking to head towards something like this.

**Comment by nokome** [comment]
I realized that we had forgotten about the `AuthorRole` node type. This will be important for the UI and for deriving metrics such as "AI influence" for each block that has `authors`.

The `authors` property is an array of the [`Author`](https://github.com/stencila/stencila/blob/main/docs/reference/schema/works/author.md) union type. In addition to `Person`, `Organization`, and `SoftwareApplication` this union includes [`AuthorRole`](https://github.com/stencila/stencila/blob/main/docs/reference/schema/works/author-role.md) which has an `author` (a `Person`, `Organization`, and a `SoftwareApplication`) and an [`AuthorRoleName`](https://github.com/stencila/stencila/blob/main/docs/reference/schema/works/author-role-name.md). I added this so that we can be more specific about who did what.

Here is an example, I showed last week taken from one of the AI assistant tests:

```json
{
  "type": "Heading",
  "level": 1,
  "content": [
    {
      "type": "Text",
      "value": "The Fastest Marine Fish Species"
    }
  ],
  "authors": [
    {
      "type": "AuthorRole",
      "author": {
        "type": "SoftwareApplication",
        "id": "openai/gpt-4-1106-preview",
        "name": "GPT"
      },
      "roleName": "Generator"
    },
    {
      "type": "AuthorRole",
      "author": {
        "type": "SoftwareApplication",
        "id": "stencila/insert-blocks",
        "name": "Insert Blocks"
      },
      "roleName": "Prompter"
    }
  ]
}
```

This is what this node looks like when encoded to "DOM HTML":

```html
<stencila-heading id=hea_11111116 level=1 root>
  <h1 slot=content>
    <stencila-text id=txt_11111111>The Fastest Marine Fish Species</stencila-text>
  </h1>
  <div slot=authors>
    <stencila-author-role id=aut_11111113 role-name=Generator>
      <stencila-software-application id=sap_11111112 @id=openai/gpt-4-1106-preview name=GPT>
      </stencila-software-application>
    </stencila-author-role>
    <stencila-author-role id=aut_11111115 role-name=Prompter>
      <stencila-software-application id=sap_11111114 @id=stencila/insert-blocks name='Insert Blocks'>
      </stencila-software-application>
    </stencila-author-role>
  </div>
</stencila-heading>
```

i.e. `<stencila-author-role>` wraps one of the "actual" author types and has a `role-name` property. We'll therefore need a Web Component for that. Note also that there are generated TypeScript types for all these things e.g. https://github.com/stencila/stencila/blob/main/ts/src/types/AuthorRoleName.ts

**Pull request merged**
