### PR TITLE
WIP: Working on Range expresssions

### PR DESCRIPTION
**Pull request by oliver----**

### CODE REVIEW

**Comment by oliver----** [comment]
image

**Comment by oliver----** [comment]
@nokome ^^
Getting closer, but...
having some troubles getting types of composites propagated through the system correctly/consistently.
Need to speed-down on this and do proper architectural design. We should specify this together

**Comment by nokome** [comment]
@oliver: great, thanks! Yes, lets discuss some more

**Comment by oliver----** [comment]
We want to produce `table` values for 2D ranges. @nokome it would be good to have libcore functions (such as `sum()`) support `table` values

**Comment by oliver----** [comment]
stencila-range-expressions

**Comment by oliver----** [comment]
@nokome ^^

**Pull request merged**
