### PR TITLE
Stencila Enhancement Proposals

### PR DESCRIPTION
**Pull request by nokome**
As discussed.

@oliver--- : this just formalises your proposal a little (and puts everything into one folder); of course, feel free to make suggestions/changes

@daniellecrobinson: if you could take a look at fleshing out step-0000.md a little that would be great

We need to avoid making this too burdensome but at the same time it would be great if these StEP documents evolve over time into useful pieces of documentation like PEPs.

### CODE REVIEW

**Comment by oliver----** [comment]
Cool. Like it.

**Comment by nokome** [comment]
> Cool. Like it.

That's a relief. Really. I need to stop worrying so much about what you guys think of my PRs :)

**Comment by oliver----** [comment]
You should stop worrying because you are pretty close to perfect.... in way to many regards ;)

**Comment by oliver----** [comment]
Seriously, my main goal is to have a process. Your proposal goes a bit further than I  considered in the beginning. but this is a better suggestion than my try.
You started the guide-line, ... I will try to consolidate the next weeks.
Probably it will be important to see how it works internally. And eventually how it is received by non-tech-savvies.

**Comment by oliver----** [comment]
Let's eat our own dog-food!

**Comment by oliver----** [comment]
Shall we merge?

**Comment by nokome** [comment]
OK, let's merge.

> Probably it will be important to see how it works internally. 

Yes absolutely, needs to work for the devs foremost.

> And eventually how it is received by non-tech-savvies.

I don't think this should ever try to reach an audience other than developers - these are intended to be *technical* design and spec docs - user guides and community forum are there for other audiences

**Pull request merged**
