### PR TITLE
Improve error display

### PR DESCRIPTION
**Pull request by oliver----**
# Why?

#669 didn't work after all. It was introducing a regression related to rerendering of the ellipses menu.

# What?
This PR tries to simplify the implementation for delayed error display, so that is closer to what I intended initially.

### CODE REVIEW

**Comment by oliver----** [comment]
stencila-better-error-display-1

**Comment by oliver----** [comment]
stencila-better-error-display-2

**Comment by oliver----** [comment]
Still it could be less jumpy to my taste... any ideas?

**Comment by oliver----** [comment]
As a comparison: the same implementation with 'display:none' instead of 'visibility:hidden'
This means, that an error is expanding only after the delay, and collapsing during typing.

stencila-better-error-display-3

**Comment by oliver----** [comment]
I like the latter better.

**Comment by oliver----** [comment]
Not there yet. Found some glitches.

**Comment by Integral** [comment]
I don't like this jumping effect at all. That's exactly what we did try to prevent during last session... And we came to that solution with visibility switching so you kind of switching between value and the error without jumping (at least for a single line value/error).

**Comment by Integral** [comment]
@oliver---- it is still have a problems... just try first code cell in repro-pub fig example, try to append numbers:

**Comment by oliver----** [comment]
Right. Also there is a flickering when blurring.

**Comment by oliver----** [comment]
But getting closer.

**Comment by oliver----** [comment]
IMO this is good now.

**Comment by Integral** [comment]
@oliver---- I think it is totally ok now.
One thing I notice is that special symbols like ö throw errors in browser while cell stays green, however this most be the other issue.

**Comment by oliver----** [comment]
@Integral Thanks!

Re exception with special symbols: can't reproduce this. Could you maybe open an issue with screenshots of the error?

**Comment by oliver----** [comment]
Merging this now.

**Pull request merged**
