### PR TITLE
Upgrade Texture

### PR DESCRIPTION
**Pull request by oliver----**
# What?
- Integrating latest Texture
- added a save hook for the local browser version the checks if a saved archive could actually be reopened

### CODE REVIEW

**Comment by nokome** [comment]
Just to let you know, I've tried this out in Stencila Desktop using `npm link stencila`. And seems to be working - some bugs and console errors, but the basics are working OK:

image

**Comment by oliver----** [comment]
We will fix the issues with serialisation and then it should be ready.

**Comment by oliver----** [comment]
We have started an integration test suite in Texture. From now on we should see regressions more easily: https://github.com/substance/texture/pull/520

**Comment by oliver----** [comment]
@nokome I found another regression in Texture I need to fix.
Working on it.

**Pull request merged**
