### PR TITLE
add in definitions, parts of a great step

### PR DESCRIPTION
**Pull request by daniellecrobinson**

### CODE REVIEW

**Comment by michael** [comment]
Good intro! Please merge docs-related any time when ready. (unless you want to get feedback first)

**Comment by oliver----** [comment]
@daniellecrobinson great to have you helping us with this :)
BTW, while you are working on a PR you can add 'WIP: ' as a prefix in the PR title. Then we know that the PR is in the work...

**Comment by daniellecrobinson** [comment]
@oliver---- ok - will do WIP in future! Thanks!

**Comment by oliver----** [comment]
Great! Thank you!

**Pull request merged**
