### PR TITLE
Provides for cells with execution in remote contexts

### PR DESCRIPTION
**Pull request by nokome**
This is still a wok in progress, don't merge yet. See #283.

### CODE REVIEW

**Comment by nokome** [comment]
@michael and @oliver---- : if you get a chance to have a look at this that would be great, otherwise, no probs I can merge it myself.

**Comment by michael** [comment]
The code looks good to me! If I wanted to try it out and run, what setup do i need to for instance execute Python code?

**Comment by nokome** [comment]
@michael : thanks! It would be great if you could user test it: install the python package:

    pip install --user https://github.com/stencila/py/archive/master.zip

and then start the host

    import stencila
    stencila.host.start()

The document should discover the host after a few seconds and allow you to use `py` or `sqlite` context. 

Oh my, so much to do for next week!

**Comment by michael** [comment]
Which Python version? I have 2.7.10 (preinstalled on OSX) but there's no pip package manger installed.

Then i run the python script as you described..  and for the Stencila UI, do I need to run the desktop app or does discovery work via the development environment?

**Comment by nokome** [comment]
2.7 is fine. pip is easiest way to install from GitHub.

Discovery works for dev setup.

By the way, you can test external code via the stencila/node package too by
running `npm start`.




On Apr 26, 2017 9:22 PM, "Michael Aufreiter" <notifications@github.com>
wrote:

Which Python version? I have 2.7.10 (preinstalled on OSX) but there's no
pip package manger installed.

Then i run the python script as you described.. and for the Stencila UI, do
I need to run the desktop app or does discovery work via the development
environment?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stencila/stencila/pull/285#issuecomment-297365669>, or mute
the thread

**Pull request merged**
