### PR TITLE
feat: #1595 #1594 impl into and merge [parents]

### PR DESCRIPTION
**Pull request by huang12zheng**
base on #1597 

1. artifacts just add two line with proc-macro
2. An example of the output can be found in the comment of proc-macro
3. limit proc-macro ‘s merge only with parent 
4. Remove any of the possible duplicates (without affecting the result)

### CODE REVIEW

**Comment by huang12zheng** [comment]
I just found out that schema filters abstract -_-||

**Comment by huang12zheng** [comment]
```
// Node union type
        // Order is important for deserialization correctness and performance since
        // serde attempts to deserialize in the order in the emum. We put primitives
        // first (for fast deserialization for kernel outputs) excecpt for `Object` which is
        // last so it does not "consume" entity types (which are also objects).
        let primitives_set = [
            "Null",
            "Boolean",
            "Integer",
            "UnsignedInteger",
            "Number",
            "String",
            "Array",
        ];
```
https://github.com/stencila/stencila/blob/main/rust/schema-gen/src/schemas.rs#L355-L362
I don't think the types here should be written dead, maybe configured in yaml and then filtered
Maybe `schema.type` has this information

**Comment by nokome** [comment]
Thanks for the PR @huang12zheng. Could you please rebase this branch onto current `main` so it is easier for me to review (given that this currently includes various other changes already accepted).

**Comment by huang12zheng** [comment]
I updated the introduction of this PR @nokome

**Comment by nokome** [comment]
Sorry for not reviewing this earlier. Given my comments in #1594 and #1595, particularly about using derive macros instead on relying on  serde, I'm going to close this PR. If you still need this functionality then please don't hesitate to let me know and I'd be happy to work with you to implement it using that approach.

**Pull request closed without merging**
