### PR TITLE
Sheets (Round 1)

### PR DESCRIPTION
**Pull request by oliver----**
Rewrite of the former prototype with the aim to provide a restrictive version for Datatables very soon.

### CODE REVIEW

**Comment by oliver----** [comment]
First version: having very flexible approach using a view-port, which is by design embeddable.
Implemented scrolling and selections.

preview-stencila-sheets-selection

preview-stencila-sheets-scrolling

**Comment by oliver----** [comment]
Row and column selections:

preview-stencila-sheets-row-and-column-selections

**Comment by oliver----** [comment]
stencila-sheets-basic-editing

**Comment by oliver----** [comment]
Keyboard nav:

**Comment by oliver----** [comment]
Need some sleep.

**Comment by nokome** [comment]
I'm unable to `npm install` this branch, even after doing `rm -rf node_modules`. Am I doing something wrong?

```sh
npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> stencila@0.27.9 prepublish /home/nokome/stencila/source/stencila
> node make

Remove: build
Remove: tmp
Copy: ./node_modules/font-awesome -> ./build/font-awesome
Copy: ./vendor/brace.* -> ./build/lib/
Copy: ./vendor/vega* -> ./build/lib/
Copy: ./vendor/unified* -> ./build/lib/
Copy: ./node_modules/d3/build/d3.min.js -> ./build/lib/
Copy: ./node_modules/katex/dist/ -> ./build/katex
Copy: ./node_modules/substance/dist/substance.js* -> ./build/lib/
Copy: ./node_modules/stencila-mini/dist/stencila-mini.js* -> ./build/lib/
PostCSS:/home/nokome/stencila/source/stencila/src/pagestyle/stencila.css->/home/nokome/stencila/source/stencila/build/stencila.css
..finished in 237 ms.
Compiling schema 'SpreadsheetSchema'...

Error during execution of Command  custom
Error: Not supported yet
Stacktrace:
Error: Not supported yet
    at _processSequence (/home/nokome/stencila/source/stencila/node_modules/substance/dist/substance/xml/compileRNG.js:182:15)
    at _compile (/home/nokome/stencila/source/stencila/node_modules/substance/dist/substance/xml/compileRNG.js:97:15)
    at compileRNG (/home/nokome/stencila/source/stencila/node_modules/substance/dist/substance/xml/compileRNG.js:26:3)
    at CustomAction.execute [as _execute] (/home/nokome/stencila/source/stencila/make.js:299:25)
    at CustomAction.execute (/home/nokome/stencila/source/stencila/node_modules/substance-bundler/src/commands/CustomCommand.js:152:33)
    at CustomCommand._executeWithoutGlob (/home/nokome/stencila/source/stencila/node_modules/substance-bundler/src/commands/CustomCommand.js:51:19)
    at CustomCommand.execute (/home/nokome/stencila/source/stencila/node_modules/substance-bundler/src/commands/CustomCommand.js:40:19)
    at Bundler._next (/home/nokome/stencila/source/stencila/node_modules/substance-bundler/src/Bundler.js:289:30)
    at Bundler._step (/home/nokome/stencila/source/stencila/node_modules/substance-bundler/src/Bundler.js:330:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by michael** [comment]
@nokome you need to do an npm link setup using the `improvements` branch of Substance.

1) in the substance repo do a `node make`
2) then do `npm link`
3) in the stencila repo do `npm link substance`

**Comment by nokome** [comment]
Thanks @michael it worked!

**Comment by oliver----** [comment]
Have finished basic work making the table rendering more flexible. 
Currently working on general table editing:

stencila-spreadsheets-insert-rows-and-cols

**Comment by nokome** [comment]
Looking nice!

**Comment by oliver----** [comment]
Basic copy'n'paste working:

stencila-spreadsheets-copy-n-paste

**Comment by oliver----** [comment]
Deleting rows and cols:

**Comment by oliver----** [comment]
More coming 2morrow!

**Comment by oliver----** [comment]
@nokome :)

**Comment by oliver----** [comment]
stencila-sheets-column-types

**Comment by oliver----** [comment]
First version of a linter:

stencila-sheet-linter

**Comment by oliver----** [comment]
We call this now the first round. Gonna merge this PR into develop.

**Comment by oliver----** [comment]
Closing this PR, because it was started on master.

**Pull request closed without merging**
