### PR TITLE
Function values

### PR DESCRIPTION
**Pull request by nokome**
# Why

Some minor fixes to deal with display and registration of functions returned from cells.

# What

Allow for display of extended types (e.g. functions); unpack functions before registering

peek 2018-05-04 19-51

### CODE REVIEW

**Comment by oliver----** [comment]
👍

**Comment by nokome** [comment]
Thanks, I'll merge this then now. Yes, it needs the latest version of stencila/node which will be in Stencila Desktop.

**Comment by michael** [comment]
Ah so this means you can't write client-side JS functions only node ones?

**Comment by oliver----** [comment]
Not yet: see https://github.com/stencila/stencila/pull/638

**Comment by nokome** [comment]
Hah, @oliver---- you beat me to it! Yes, specifically https://github.com/stencila/stencila/pull/638#issuecomment-386527149

Right now the `stencila/node/JavascriptContext` handles functions but nothing else, and the `stencila/stencila/JsContext` does everything else. We need to merge the functionality into one. I was planning to do that today but got caught up with a bunch of other fixes :man_shrugging:

**Pull request merged**
