### PR TITLE
Update Transclusions

### PR DESCRIPTION
**Pull request by oliver----**
# Why?

At the moment, transclusions are not updated when changing the structure of a referenced sheet or changing the name of a referenced document.

# What?

Introducing a hook on project level, that updates all affected transclusions appropriately.

### CODE REVIEW

**Comment by oliver----** [comment]
I'd like to merge this and do another iteration with fixes later.
@michael or @nokome can I have green light for merging? Maybe you would like to try out before that.

**Comment by oliver----** [comment]
Ah, wait. I spotted one thing I wanted to do: Updating transclusions when the sheet is renamed.

**Comment by oliver----** [comment]
I brought back codecov.io report.
As a final iteration on this PR, I will add tests for the transclusion implementation.
After this PR, I will do an iteration test-covering the rest of the existing implementation.

**Comment by oliver----** [comment]
Shame on me!
But I will merge now, so I can continue on my testing mission.

**Comment by nokome** [comment]
@oliver---- thanks for this! Sorry for not responding earlier, it slipped down my inbox.

**Pull request merged**
