### PR TITLE
Cell referencing

### PR DESCRIPTION
**Pull request by Integral**
Not ready yet.

### CODE REVIEW

**Comment by oliver----** [comment]
OMG :)

**Comment by oliver----** [comment]
image

**Comment by oliver----** [comment]
dxdnwllbeq

**Comment by oliver----** [comment]
@nokome ^^

**Comment by nokome** [comment]
Woah, awesome @Integral !

**Comment by michael** [comment]
Yeah, bravo! :)

Next we need a addCellMarkers API to color the range while dragging but also other ranges in the expression. What is also important is a tokenizer so we can implement a replace range functionality as well as detecting all the ranges of an expression.

**Comment by oliver----** [comment]
The tokens are there. Just need to provide an API to get the current token.

**Comment by Integral** [comment]
It was Michael's idea, I'm just an implementer behind ;)

**Comment by michael** [comment]
Cool. We thought of adding such API's on a custom CellEditorSession. The CodeEditor would be the wrong place as there are multiple instances of it?

**Comment by oliver----** [comment]
The tokens are on the cell.

**Comment by michael** [comment]
Thought of something like this:

```js
cellEditorSession.replaceSelectedToken('A1:C5')
```

or better just a helper?

```js
replaceSelectedToken(cellEditorSession, 'A1:C4')
```

**Comment by michael** [comment]
Merging this and calling it a day. See you tomorrow!

**Comment by oliver----** [comment]
Cool. CU 2morrow.

**Pull request merged**
